name: dp-federated-learning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=22.0.0
  - flake8>=4.0.0
  - pip:
    - torch>=2.0.0
    - torchvision>=0.15.0
    - opacus>=1.4.0
    - flwr>=1.4.0
    - streamlit>=1.20.0
    - plotly>=5.0.0
    - shap>=0.40.0
    - tqdm>=4.62.0
    - pyyaml>=6.0
    - pathlib2>=2.3.0 